// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * l​e​o​v​o​o​n
	 */
	AUTHOR: string
}

export type TranslationFunctions = {
	/**
	 * leovoon
	 */
	AUTHOR: () => LocalizedString
}

export type Formatters = {}
